# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        services:
          - docker
        script:
          - sudo curl https://cli-assets.heroku.com/install.sh | sh
          - cd Backend\ service/AutoGatrorBackend
          - heroku container:login
          - heroku container:push -a autogator-servcie web
          - heroku container:release -a autogator-servcie web

