# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    develop:
      - step:
          name: 'Deployment to Staging'
          deployment: staging
          services:
            - docker
          script:
            - curl https://cli-assets.heroku.com/install.sh | sh
            - cd Backend\ service/AutoGatrorBackend
            - HEROKU_API_KEY=$HEROKU_TOKEN heroku container:login
            - HEROKU_API_KEY=$HEROKU_TOKEN heroku container:push -a autogator-servcie web
            - HEROKU_API_KEY=$HEROKU_TOKEN heroku container:release -a autogator-servcie web 

